### ISSUE TITLE
Debug Print 기능

### ISSUE THREAD

**Issue by junah201** [haruharo101/snippet_for_PS_Cpp_VSCode#3]
@haruharo101 

누구나 한번 쯤은 깜빡하고 디버그 프린트문을 안지우고 제출해서 틀린 경험이 있을 것 입니다. 
이것을 방지하기 위해 백준 등의 온라인 저지에서는 `ONLINE_JUDGE` 옵션을 제공합니다.

```c++
#ifndef ONLINE_JUDGE
    printf("[DEBUG] Add edge (%d, %d)\n", v1, v2);
#endif
```

위와 같이 출력할 경우 로컬에서는 해당 프린트가 보이지만, 백준 채점기에서는 지워지고 컴파일 되기 때문에 출력되지 않습니다.
즉 그냥 소스 수정 안하고 제출해도 디버깅용 문자열 출력이 알아서 지워진다는 것이죠.

단 위의 방식에는 큰 단점이 있습니다. 저 `#ifndef ONLINE_JUDGE` 이 부분이 너무 길어서 적기 귀찮다는 것이죠.

따라서 저는 아래와 같이 따로 디버그용 프린트문을 함수로 선언해서 사용합니다.

```C++
void dprintf(const char *__format, ...)
{
#ifndef ONLINE_JUDGE
    printf(__format);
#endif
}
```

또한 PS를 할때 자주 사용하는 [CPH](https://marketplace.visualstudio.com/items?itemName=DivyanshuAgrawal.competitive-programming-helper) 확장에서도 `Set ONLINE_JUDGE` 컴파일 옵션을 제공합니다.

![image](https://user-images.githubusercontent.com/75025529/188417095-3ecafd7b-542e-4558-829d-14ba8e99db72.png)

결론적으로 이러한 함수가 `PS snippet`에 포함되면 좋을 것 같습니다.
(hd에 기본적으로 선언되거나, 따로 스프린트를 제작하면 좋을 것 같습니다.)

긍정적으로 생각하신다면 풀 리퀘스트를 넣어도 될까요?

---
관련 링크 : https://www.acmicpc.net/blog/view/110

**Comment by haruharo101** [comment]
Okay
